### ISSUE TITLE
Virtualbox has different apt key for Debian Jessie and Ubuntu Xenial

### ISSUE THREAD

**Issue by sysadmiral** [danzilio/danzilio-virtualbox#29]
According to the page at [virtualbox](https://www.virtualbox.org/wiki/Linux_Downloads#Debian-basedLinuxdistributions) there is now a new key for Debian Jessie and Ubuntu Xenial.

The key thumbprint is: "B9F8D658297AF3EFC18D5CDFA2F683C52980AECF"

The key source is: https://www.virtualbox.org/download/oracle_vbox_2016.asc

I am about to submit a PR that should address this but I am testing it on first:

* debian jessie
* debian !jessie
* ubuntu xenial
* ubuntu !xenial

I will submit the PR once I have tested.

**Comment by danzilio** [comment]
@sysadmiral Thank you!!!

**Comment by TomaszUrugOlszewski** [comment]
Hello danzilio & sysadmiral

Do you plan to merge it to master soon?

**Comment by sysadmiral** [comment]
This has been merged but can you release a corresponding forge module please @danzilio?

**Comment by danzilio** [comment]
I'll get a new release out early next week! I still have a few other things to do with this module before cutting a new release. I'll post here once I've got a release out.

**Comment by danzilio** [comment]
Released in v1.7.1
