### ISSUE TITLE
typo: githun instead of github in extpack.pp

### ISSUE THREAD

**Issue by hdeadman** [danzilio/danzilio-virtualbox#31]
Line 73 of extpack.pp:
      /githun\.com\/(puppet-community|voxpupuli)/ => 'voxpupuli',

Should be github vs. githun results in the following error:

Evaluation Error: No matching entry for selector parameter with value 'https://github.com/puppet-community/puppet-archive' at /etc/puppetlabs/code/3rdparty/modules/virtualbox/manifests/extpack.pp:71:18

**Comment by danzilio** [comment]
Whoops! I'll get a patch out for this today!

**Comment by danzilio** [comment]
fixed in 4d8af98
