### ISSUE TITLE
Predicting a bugfix release?

### ISSUE THREAD

**Issue by hunner** [danzilio/danzilio-virtualbox#8]
It looks like 1.2.2 is in the metadata but only 1.2.1 is released on the forge. Is this on purpose because the release is pending? What if the next release has a feature instead of a bugfix?

If you could keep a changelog documenting that it is a pending release, that would be great! http://keepachangelog.com/ documents a great changelog layout. (And it would be helpful to see the semantic versioned changes between releases.)

**Comment by danzilio** [comment]
Hey Hunter! Thanks for the feedback! I'll put together a backdated changelog tonight, with the intent on keeping it updated in the future.

As for the version being 1.2.2 in the metadata, I tend to use the `release` rake task in blacksmith that automatically increments the patch level in anticipation for the next release. I don't have anything planned for 1.2.2 yet (although I've been contemplating removing the dependency on `camptocamp/archive` from metadata and noting it in the README, as it's not essential for the core functionality of the module). If we do introduce a new feature, I would release it as 1.3.0.

**Comment by danzilio** [comment]
@hunner if you agree that this is resolved with #9, I'll go ahead and close this issue.
